workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: pt.megacachorro.megadelivery
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Set up iOS code signing
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles
          find "$HOME/Library/MobileDevice/Provisioning Profiles" -name "*.mobileprovision" -print
      - name: Run tests
        script: flutter test
      - name: Build iOS IPA
        script: |
          flutter build ios --release --no-codesign
          xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
